print("anshu")
print("king")
print("Anshu Raj")
print("queen")
print("queen")
print("prince")
print("princess")
print("emperor")
print("empress")        
print("duke")
print("duchess")
print("prince")
print("Saloni & Anshu")
